# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PyCurve_2D.ui'
#
# Created: Sun May 25 20:57:42 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PyCurve_2D(object):
    def setupUi(self, PyCurve_2D):
        PyCurve_2D.setObjectName(_fromUtf8("PyCurve_2D"))
        PyCurve_2D.resize(1000, 621)
        PyCurve_2D.setMaximumSize(QtCore.QSize(1000, 621))
        self.centralwidget = QtGui.QWidget(PyCurve_2D)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.line = QtGui.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 300, 1001, 41))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.OneDimFile = QtGui.QComboBox(self.centralwidget)
        self.OneDimFile.setGeometry(QtCore.QRect(10, 460, 871, 31))
        self.OneDimFile.setObjectName(_fromUtf8("OneDimFile"))
        self.TwoDimFile = QtGui.QComboBox(self.centralwidget)
        self.TwoDimFile.setGeometry(QtCore.QRect(10, 420, 871, 31))
        self.TwoDimFile.setObjectName(_fromUtf8("TwoDimFile"))
        self.Browse_1D = QtGui.QPushButton(self.centralwidget)
        self.Browse_1D.setGeometry(QtCore.QRect(890, 460, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.Browse_1D.setFont(font)
        self.Browse_1D.setObjectName(_fromUtf8("Browse_1D"))
        self.Browse_2D = QtGui.QPushButton(self.centralwidget)
        self.Browse_2D.setGeometry(QtCore.QRect(890, 420, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.Browse_2D.setFont(font)
        self.Browse_2D.setIconSize(QtCore.QSize(15, 16))
        self.Browse_2D.setObjectName(_fromUtf8("Browse_2D"))
        self.CheckMeshQ_skewness = QtGui.QCheckBox(self.centralwidget)
        self.CheckMeshQ_skewness.setEnabled(True)
        self.CheckMeshQ_skewness.setGeometry(QtCore.QRect(120, 490, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.CheckMeshQ_skewness.setFont(font)
        self.CheckMeshQ_skewness.setObjectName(_fromUtf8("CheckMeshQ_skewness"))
        self.CheckTPS = QtGui.QCheckBox(self.centralwidget)
        self.CheckTPS.setEnabled(True)
        self.CheckTPS.setGeometry(QtCore.QRect(390, 510, 16, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.CheckTPS.setFont(font)
        self.CheckTPS.setText(_fromUtf8(""))
        self.CheckTPS.setObjectName(_fromUtf8("CheckTPS"))
        self.CheckCPC2 = QtGui.QCheckBox(self.centralwidget)
        self.CheckCPC2.setEnabled(True)
        self.CheckCPC2.setGeometry(QtCore.QRect(450, 510, 16, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.CheckCPC2.setFont(font)
        self.CheckCPC2.setText(_fromUtf8(""))
        self.CheckCPC2.setObjectName(_fromUtf8("CheckCPC2"))
        self.CheckCPC2b = QtGui.QCheckBox(self.centralwidget)
        self.CheckCPC2b.setEnabled(True)
        self.CheckCPC2b.setGeometry(QtCore.QRect(510, 510, 16, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.CheckCPC2b.setFont(font)
        self.CheckCPC2b.setText(_fromUtf8(""))
        self.CheckCPC2b.setObjectName(_fromUtf8("CheckCPC2b"))
        self.CheckCPC4 = QtGui.QCheckBox(self.centralwidget)
        self.CheckCPC4.setEnabled(True)
        self.CheckCPC4.setGeometry(QtCore.QRect(570, 510, 16, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.CheckCPC4.setFont(font)
        self.CheckCPC4.setText(_fromUtf8(""))
        self.CheckCPC4.setObjectName(_fromUtf8("CheckCPC4"))
        self.CheckCPC6 = QtGui.QCheckBox(self.centralwidget)
        self.CheckCPC6.setEnabled(True)
        self.CheckCPC6.setGeometry(QtCore.QRect(630, 510, 16, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.CheckCPC6.setFont(font)
        self.CheckCPC6.setText(_fromUtf8(""))
        self.CheckCPC6.setObjectName(_fromUtf8("CheckCPC6"))
        self.Generate = QtGui.QPushButton(self.centralwidget)
        self.Generate.setGeometry(QtCore.QRect(670, 500, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.Generate.setFont(font)
        self.Generate.setObjectName(_fromUtf8("Generate"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 500, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.InnerBound = QtGui.QLineEdit(self.centralwidget)
        self.InnerBound.setGeometry(QtCore.QRect(10, 330, 301, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.InnerBound.setFont(font)
        self.InnerBound.setObjectName(_fromUtf8("InnerBound"))
        self.OuterBound = QtGui.QLineEdit(self.centralwidget)
        self.OuterBound.setGeometry(QtCore.QRect(320, 330, 301, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.OuterBound.setFont(font)
        self.OuterBound.setObjectName(_fromUtf8("OuterBound"))
        self.Order = QtGui.QLineEdit(self.centralwidget)
        self.Order.setGeometry(QtCore.QRect(10, 370, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.Order.setFont(font)
        self.Order.setObjectName(_fromUtf8("Order"))
        self.Radius = QtGui.QLineEdit(self.centralwidget)
        self.Radius.setGeometry(QtCore.QRect(230, 370, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.Radius.setFont(font)
        self.Radius.setObjectName(_fromUtf8("Radius"))
        self.CTPS_Radius = QtGui.QLineEdit(self.centralwidget)
        self.CTPS_Radius.setGeometry(QtCore.QRect(430, 370, 191, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.CTPS_Radius.setFont(font)
        self.CTPS_Radius.setObjectName(_fromUtf8("CTPS_Radius"))
        self.OutputFile = QtGui.QLineEdit(self.centralwidget)
        self.OutputFile.setGeometry(QtCore.QRect(10, 540, 321, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.OutputFile.setFont(font)
        self.OutputFile.setObjectName(_fromUtf8("OutputFile"))
        self.Graph1 = QtGui.QWidget(self.centralwidget)
        self.Graph1.setGeometry(QtCore.QRect(0, 0, 501, 321))
        self.Graph1.setObjectName(_fromUtf8("Graph1"))
        self.Graph2 = QtGui.QWidget(self.centralwidget)
        self.Graph2.setGeometry(QtCore.QRect(500, 0, 501, 321))
        self.Graph2.setObjectName(_fromUtf8("Graph2"))
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(490, 10, 21, 311))
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.ShowTime = QtGui.QLCDNumber(self.centralwidget)
        self.ShowTime.setGeometry(QtCore.QRect(580, 540, 131, 31))
        self.ShowTime.setDigitCount(9)
        self.ShowTime.setMode(QtGui.QLCDNumber.Oct)
        self.ShowTime.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.ShowTime.setObjectName(_fromUtf8("ShowTime"))
        self.line_3 = QtGui.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(620, 320, 20, 91))
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.Stop = QtGui.QPushButton(self.centralwidget)
        self.Stop.setGeometry(QtCore.QRect(780, 500, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.Stop.setFont(font)
        self.Stop.setObjectName(_fromUtf8("Stop"))
        self.Reset = QtGui.QPushButton(self.centralwidget)
        self.Reset.setGeometry(QtCore.QRect(890, 500, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        self.Reset.setFont(font)
        self.Reset.setObjectName(_fromUtf8("Reset"))
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(-3, 395, 1001, 31))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(480, 540, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.VincentLab = QtGui.QLabel(self.centralwidget)
        self.VincentLab.setGeometry(QtCore.QRect(770, 540, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.VincentLab.setFont(font)
        self.VincentLab.setObjectName(_fromUtf8("VincentLab"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(670, 320, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.delta_y = QtGui.QLineEdit(self.centralwidget)
        self.delta_y.setGeometry(QtCore.QRect(710, 370, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.delta_y.setFont(font)
        self.delta_y.setObjectName(_fromUtf8("delta_y"))
        self.pivot_x = QtGui.QLineEdit(self.centralwidget)
        self.pivot_x.setGeometry(QtCore.QRect(790, 370, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.pivot_x.setFont(font)
        self.pivot_x.setObjectName(_fromUtf8("pivot_x"))
        self.pivot_y = QtGui.QLineEdit(self.centralwidget)
        self.pivot_y.setGeometry(QtCore.QRect(860, 370, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.pivot_y.setFont(font)
        self.pivot_y.setObjectName(_fromUtf8("pivot_y"))
        self.rot_degree = QtGui.QLineEdit(self.centralwidget)
        self.rot_degree.setGeometry(QtCore.QRect(930, 370, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.rot_degree.setFont(font)
        self.rot_degree.setObjectName(_fromUtf8("rot_degree"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(660, 340, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(770, 320, 20, 91))
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.label_10 = QtGui.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(830, 320, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(800, 340, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_13 = QtGui.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(930, 340, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.delta_x = QtGui.QLineEdit(self.centralwidget)
        self.delta_x.setGeometry(QtCore.QRect(640, 370, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.delta_x.setFont(font)
        self.delta_x.setObjectName(_fromUtf8("delta_x"))
        self.ShowState = QtGui.QLabel(self.centralwidget)
        self.ShowState.setGeometry(QtCore.QRect(380, 540, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setItalic(True)
        self.ShowState.setFont(font)
        self.ShowState.setMouseTracking(True)
        self.ShowState.setFrameShape(QtGui.QFrame.WinPanel)
        self.ShowState.setFrameShadow(QtGui.QFrame.Sunken)
        self.ShowState.setLineWidth(2)
        self.ShowState.setMidLineWidth(2)
        self.ShowState.setTextFormat(QtCore.Qt.RichText)
        self.ShowState.setAlignment(QtCore.Qt.AlignCenter)
        self.ShowState.setObjectName(_fromUtf8("ShowState"))
        self.CheckMeshQ_nonorth = QtGui.QCheckBox(self.centralwidget)
        self.CheckMeshQ_nonorth.setEnabled(True)
        self.CheckMeshQ_nonorth.setGeometry(QtCore.QRect(120, 510, 131, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.CheckMeshQ_nonorth.setFont(font)
        self.CheckMeshQ_nonorth.setObjectName(_fromUtf8("CheckMeshQ_nonorth"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(255, 500, 121, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(340, 540, 31, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.TPS_label = QtGui.QLabel(self.centralwidget)
        self.TPS_label.setGeometry(QtCore.QRect(383, 490, 31, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.TPS_label.setFont(font)
        self.TPS_label.setObjectName(_fromUtf8("TPS_label"))
        self.CPC2_label = QtGui.QLabel(self.centralwidget)
        self.CPC2_label.setGeometry(QtCore.QRect(440, 490, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.CPC2_label.setFont(font)
        self.CPC2_label.setObjectName(_fromUtf8("CPC2_label"))
        self.CPC2_label_2 = QtGui.QLabel(self.centralwidget)
        self.CPC2_label_2.setGeometry(QtCore.QRect(490, 490, 61, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.CPC2_label_2.setFont(font)
        self.CPC2_label_2.setObjectName(_fromUtf8("CPC2_label_2"))
        self.CPC2_label_3 = QtGui.QLabel(self.centralwidget)
        self.CPC2_label_3.setGeometry(QtCore.QRect(560, 490, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.CPC2_label_3.setFont(font)
        self.CPC2_label_3.setObjectName(_fromUtf8("CPC2_label_3"))
        self.CPC6_label = QtGui.QLabel(self.centralwidget)
        self.CPC6_label.setGeometry(QtCore.QRect(620, 490, 41, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.CPC6_label.setFont(font)
        self.CPC6_label.setObjectName(_fromUtf8("CPC6_label"))
        self.VincentLab_2 = QtGui.QLabel(self.centralwidget)
        self.VincentLab_2.setGeometry(QtCore.QRect(880, 540, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.VincentLab_2.setFont(font)
        self.VincentLab_2.setObjectName(_fromUtf8("VincentLab_2"))
        PyCurve_2D.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(PyCurve_2D)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        PyCurve_2D.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(PyCurve_2D)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        PyCurve_2D.setStatusBar(self.statusbar)

        self.retranslateUi(PyCurve_2D)
        QtCore.QMetaObject.connectSlotsByName(PyCurve_2D)
        PyCurve_2D.setTabOrder(self.InnerBound, self.OuterBound)
        PyCurve_2D.setTabOrder(self.OuterBound, self.Order)
        PyCurve_2D.setTabOrder(self.Order, self.Radius)
        PyCurve_2D.setTabOrder(self.Radius, self.CTPS_Radius)
        PyCurve_2D.setTabOrder(self.CTPS_Radius, self.delta_x)
        PyCurve_2D.setTabOrder(self.delta_x, self.delta_y)
        PyCurve_2D.setTabOrder(self.delta_y, self.pivot_x)
        PyCurve_2D.setTabOrder(self.pivot_x, self.pivot_y)
        PyCurve_2D.setTabOrder(self.pivot_y, self.rot_degree)
        PyCurve_2D.setTabOrder(self.rot_degree, self.Browse_2D)
        PyCurve_2D.setTabOrder(self.Browse_2D, self.Browse_1D)
        PyCurve_2D.setTabOrder(self.Browse_1D, self.CheckMeshQ_skewness)
        PyCurve_2D.setTabOrder(self.CheckMeshQ_skewness, self.CheckMeshQ_nonorth)
        PyCurve_2D.setTabOrder(self.CheckMeshQ_nonorth, self.CheckTPS)
        PyCurve_2D.setTabOrder(self.CheckTPS, self.CheckCPC2)
        PyCurve_2D.setTabOrder(self.CheckCPC2, self.CheckCPC2b)
        PyCurve_2D.setTabOrder(self.CheckCPC2b, self.CheckCPC4)
        PyCurve_2D.setTabOrder(self.CheckCPC4, self.CheckCPC6)
        PyCurve_2D.setTabOrder(self.CheckCPC6, self.OutputFile)
        PyCurve_2D.setTabOrder(self.OutputFile, self.Generate)
        PyCurve_2D.setTabOrder(self.Generate, self.Stop)
        PyCurve_2D.setTabOrder(self.Stop, self.Reset)
        PyCurve_2D.setTabOrder(self.Reset, self.TwoDimFile)
        PyCurve_2D.setTabOrder(self.TwoDimFile, self.OneDimFile)

    def retranslateUi(self, PyCurve_2D):
        PyCurve_2D.setWindowTitle(_translate("PyCurve_2D", "PyCurve_2D", None))
        self.Browse_1D.setText(_translate("PyCurve_2D", "Browse 1D Mesh", None))
        self.Browse_2D.setText(_translate("PyCurve_2D", "Browse 2D Mesh", None))
        self.CheckMeshQ_skewness.setText(_translate("PyCurve_2D", "Skewness", None))
        self.Generate.setText(_translate("PyCurve_2D", "Generate", None))
        self.label_2.setText(_translate("PyCurve_2D", "Optimisation by", None))
        self.InnerBound.setPlaceholderText(_translate("PyCurve_2D", "Inner Boundary Lines Separated by Commas", None))
        self.OuterBound.setPlaceholderText(_translate("PyCurve_2D", "Outer Boundary Lines Separated by Commas", None))
        self.Order.setPlaceholderText(_translate("PyCurve_2D", "Mesh Order", None))
        self.Radius.setPlaceholderText(_translate("PyCurve_2D", "Local RBF Radius", None))
        self.CTPS_Radius.setPlaceholderText(_translate("PyCurve_2D", "CTPS Radius", None))
        self.OutputFile.setPlaceholderText(_translate("PyCurve_2D", "Specify The Output File Name", None))
        self.Stop.setText(_translate("PyCurve_2D", "Stop", None))
        self.Reset.setText(_translate("PyCurve_2D", "Reset", None))
        self.label_3.setText(_translate("PyCurve_2D", "Elapsed Time", None))
        self.VincentLab.setText(_translate("PyCurve_2D", "<html><head/><body><p><span style=\" color:#0000ff;\">Vincent Lab @</span></p></body></html>", None))
        self.label_5.setText(_translate("PyCurve_2D", "Translation", None))
        self.delta_y.setPlaceholderText(_translate("PyCurve_2D", "Y Axis", None))
        self.pivot_x.setPlaceholderText(_translate("PyCurve_2D", "X Axis", None))
        self.pivot_y.setPlaceholderText(_translate("PyCurve_2D", "Y Axis", None))
        self.rot_degree.setPlaceholderText(_translate("PyCurve_2D", "Degree", None))
        self.label_6.setText(_translate("PyCurve_2D", "In Unit Length", None))
        self.label_10.setText(_translate("PyCurve_2D", "Rotation in Degrees", None))
        self.label_8.setText(_translate("PyCurve_2D", "Pivot Coordinate", None))
        self.label_13.setText(_translate("PyCurve_2D", "Rotation", None))
        self.delta_x.setPlaceholderText(_translate("PyCurve_2D", "X Axis", None))
        self.ShowState.setText(_translate("PyCurve_2D", "Idle States", None))
        self.CheckMeshQ_nonorth.setText(_translate("PyCurve_2D", "Nonorthgonality", None))
        self.label_7.setText(_translate("PyCurve_2D", ", or Generation by", None))
        self.label_9.setText(_translate("PyCurve_2D", ".msh", None))
        self.TPS_label.setText(_translate("PyCurve_2D", "TPS", None))
        self.CPC2_label.setText(_translate("PyCurve_2D", "<html><head/><body><p>CPC<span style=\" vertical-align:super;\">2</span></p></body></html>", None))
        self.CPC2_label_2.setText(_translate("PyCurve_2D", "<html><head/><body><p>CTPSC<span style=\" vertical-align:super;\">2</span><span style=\" vertical-align:sub;\">b</span></p></body></html>", None))
        self.CPC2_label_3.setText(_translate("PyCurve_2D", "<html><head/><body><p>CPC<span style=\" vertical-align:super;\">4</span></p></body></html>", None))
        self.CPC6_label.setText(_translate("PyCurve_2D", "<html><head/><body><p>CPC<span style=\" vertical-align:super;\">6</span></p></body></html>", None))
        self.VincentLab_2.setText(_translate("PyCurve_2D", "<html><head/><body><p><img src=\":/images/icon1.png\"/></p></body></html>", None))

import icon_rc
